In [1]:
#!/usr/bin/env python3
import time
import numpy as np
from math import *
import matplotlib.pyplot as plt
from scipy import interpolate

In [2]:
#urx for ur10 and gripper
import urx
import math3d as m3d
from urx.robotiq_two_finger_gripper import Robotiq_Two_Finger_Gripper
ur = urx.Robot("192.168.1.102")
gripper = Robotiq_Two_Finger_Gripper(ur)
ur.set_tcp((0, 0, 0, 0, 0, 0))
tcp_acc=0.05
tcp_vel=0.05
time.sleep(0.2)
pose = ur.get_pose()
print(pose)

<Transform:
<Orientation: 
array([[ 9.99999997e-01, -1.02598458e-05, -8.00494962e-05],
       [-1.02572698e-05, -9.99999999e-01,  3.21798675e-05],
       [-8.00498263e-05, -3.21790463e-05, -9.99999996e-01]])>
<Vector: (-0.08997, 0.48651, 0.40321)>
>


In [3]:
import palm

finding an odrive...
Odrive Voltage: 13.302319526672363


In [104]:
palm.disable_motor()

disabling motor control...


## init hardware

In [4]:
gripper.gripper_activate()
time.sleep(1)
ur.set_tcp((0, 0, 0.295, 0, 0, 0)) #upper jaw's tip to tool0 29.5mm
int_list=np.array([0,170, 175, 180, 185, 190, 195, 200, 205, 210, 215,250])
distance_list= np.array([118,28,25,22,19,17,14,10,8,5,2,0])/1000.0 
func_from_distance_to_int = interpolate.interp1d(distance_list, int_list, kind = 3)
grasp_width = 0.1
gripper.gripper_action(int(func_from_distance_to_int(grasp_width))) 

In [50]:
palm.home()

homing...
enabling motor control...


#### pick object

In [95]:
palm.home()
gripper.gripper_action(int(func_from_distance_to_int(grasp_width))) 
ur.movel((-0.09, 0.4865, 0.005, 3.1, 0, 0.5), tcp_acc, tcp_vel)

homing...
enabling motor control...


<Transform:
<Orientation: 
array([[ 9.49354460e-01, -1.28937823e-04,  3.14207085e-01],
       [ 3.70788730e-04, -9.99998760e-01, -1.53067076e-03],
       [ 3.14206893e-01,  1.56965356e-03, -9.49353235e-01]])>
<Vector: (-0.09002, 0.48645, 0.00500)>
>

In [96]:
# drop_pose = ur.getl()
# drop_pose[2] = drop_pose[2]-0.033
# ur.movel(drop_pose, tcp_acc, tcp_vel)
ur.movel((-0.08997965418486337,0.4865784613324623,-0.02797709706841575,3.0421275633240077,-0.00012291556244661,0.7783613527132803), tcp_acc, tcp_vel)
time.sleep(0.5)

In [97]:
palm.goto((0,135))
time.sleep(0.5)
palm.goto((-5,140))
time.sleep(0.5)
palm.rotate((-5,140), (-8,110), 70, 1)
time.sleep(0.5)
palm.goto((-35,125))

Rotated to: (-35.04591707504916, 123.32360197429976)


In [98]:
lift = ur.getl()
lift[2] = lift[2]+0.03
ur.movel(lift, tcp_acc, tcp_vel)
ur.movel((-0.09, 0.4865, 0.005, pi, 0, 0), tcp_acc, tcp_vel)

<Transform:
<Orientation: 
array([[ 9.99999969e-01, -1.18225056e-04,  2.19806365e-04],
       [-1.18204578e-04, -9.99999989e-01, -9.31746427e-05],
       [ 2.19817378e-04,  9.31486577e-05, -9.99999972e-01]])>
<Vector: (-0.08997, 0.48654, 0.00498)>
>

In [99]:
# palm.goto((-30,130))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.07)),150) 

In [100]:
palm.goto((-10,145))
time.sleep(0.5)
palm.goto((0,117))
time.sleep(0.07)
palm.goto((-15,117))
time.sleep(0.5)
palm.goto((-15,139))
time.sleep(0.5)
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.049)),30) 
time.sleep(0.5)
palm.set_hard()
palm.goto((-15,142))
time.sleep(1)
palm.enable_motor()

enabling motor control...


In [101]:
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.07)),30) 

In [102]:
palm.goto((-15,137))
time.sleep(0.5)
palm.goto((20,145))

In [103]:
palm.goto((-30,137))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.02)),30) 

In [715]:
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.04)),30) 

## reorient_pp

In [52]:
### init gripper
gripper.gripper_activate()
time.sleep(1)
ur.set_tcp((0, 0, 0.295, 0, 0, 0)) #upper jaw's tip to tool0 29.5mm
int_list=np.array([0,170, 175, 180, 185, 190, 195, 200, 205, 210, 215,250])
distance_list= np.array([130,31,28,25,22,19,15,13,9,7,4,0])/1000.0 
func_from_distance_to_int = interpolate.interp1d(distance_list, int_list, kind = 3)
center_width = 0.057 #jawtip at center of gripper:0.057
gripper.gripper_action(int(func_from_distance_to_int(center_width+0.02))) 

In [53]:
### init palm
palm.enable_motor()
# write_angle(inverse_kinematics((15,150)))
palm.goto((15,150))

enabling motor control...


In [50]:
### go pick pose
# print(ur.getl())
ur.movel((-0.09, 0.4865, 0.005, pi, 0, 0), tcp_acc, tcp_vel)
### close gripper and palm
grasp_width = center_width+0.012 #elliptical 
gripper.gripper_action(int(func_from_distance_to_int(grasp_width)))
time.sleep(0.1)
palm.goto((0,150))
### lift up
lift_pose = ur.getl()
lift_pose[2] = lift_pose[2]+0.07
ur.movel(lift_pose, tcp_acc, tcp_vel)
### open gripper
palm.goto((-10,150))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width+0.015)))
time.sleep(0.5)
### reorient object
normal_reorient = 1
if normal_reorient == 1:
    ### reorient object
    palm.rotate((-10,146), (-15,150), -80, 1)
else: # pivot up and down
    palm.goto((-15,158))
    time.sleep(1)
    palm.goto((-23,159))
    time.sleep(1)
    palm.goto((-10,150))
    time.sleep(1)
    palm.goto((-15,140))
    time.sleep(1)
#     new_pos = palm.rotate((-5,150), (-10,150), 100, 0.5)
#     time.sleep(0.5)
#     new_pos = palm.rotate(new_pos, (-10,150), -150, 0.5)
time.sleep(1)
### close gripper
palm.goto((-10,130))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.02)))
# palm.goto((0,110))

Rotated to: (-18.039695639734642, 144.36437666111564)


#### release single object

In [24]:
### open gripper and ready for reorient
palm.goto((0,130))
time.sleep(0.5)
palm.goto((-10,150))
time.sleep(0.5)
gripper.gripper_action(int(func_from_distance_to_int(grasp_width+0.01)))
time.sleep(0.5)

### reorient
palm.rotate((-10,150), (-5,150), 80, 1)
time.sleep(1.5)

### close gripper
palm.goto((-5,145))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.004)))

### lower robot
drop_pose = ur.getl()
drop_pose[1] = drop_pose[1]-0.0015
drop_pose[2] = drop_pose[2]-0.075
ur.movel(drop_pose, tcp_acc, tcp_vel)

### release object
palm.goto((13,150))
gripper.gripper_action(int(func_from_distance_to_int(center_width+0.02))) 

lift_pose = ur.getl()
lift_pose[2] = lift_pose[2]+0.07
ur.movel(lift_pose, tcp_acc, tcp_vel)

-5.8965368076764095 145.08103448350352
Rotated to: (-5.8965368076764095, 145.08103448350352)


<Transform:
<Orientation: 
array([[ 9.99999991e-01, -6.63155641e-05,  1.17606562e-04],
       [-6.63346776e-05, -9.99999985e-01,  1.62524735e-04],
       [ 1.17595783e-04, -1.62532535e-04, -9.99999980e-01]])>
<Vector: (-0.08983, 0.48509, 0.07016)>
>

#### pick next object

In [51]:
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.01)))
palm.goto((-20,130))
time.sleep(1)
palm.goto((-20,140))
time.sleep(1)
palm.goto((15,140))
time.sleep(1)

gripper.gripper_action(int(func_from_distance_to_int(center_width+0.02))) 
palm.goto((15,150))
time.sleep(0.5)

ur.movel((-0.09, 0.485, 0.005, pi, 0, 0), tcp_acc, tcp_vel)
time.sleep(0.5)

grasp_width = center_width+0.012 #elliptical 
gripper.gripper_action(int(func_from_distance_to_int(grasp_width)))
time.sleep(0.1)
palm.goto((0,150))
time.sleep(0.5)

lift_pose = ur.getl()
lift_pose[2] = lift_pose[2]+0.07
ur.movel(lift_pose, tcp_acc, tcp_vel)
time.sleep(0.5)

palm.goto((-10,150))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width+0.010)))
time.sleep(1)

palm.rotate((-10,146), (-15,150), -80, 1)
time.sleep(1)

palm.goto((-10,130))
gripper.gripper_action(int(func_from_distance_to_int(grasp_width-0.02)))
time.sleep(1)

Rotated to: (-18.05674455264937, 144.37360570704038)


In [74]:
palm.disable_motor()

disabling motor control...


In [75]:
palm.enable_motor()

enabling motor control...


In [63]:
palm.home()

homing...
enabling motor control...


In [30]:
palm.get_pos()

(0.0815746470001075, 77.72131715725102)

In [62]:
palm.set_soft()

In [57]:
palm.set_hard()

In [76]:
for i in range(3):
    palm.goto((-30,70))
    time.sleep(0.07)
    palm.goto((30,70))
    time.sleep(0.07)
    palm.goto((0,150))
    time.sleep(0.07)